inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - config/**/*
    - db/**/*
    - bin/setup
    - vendor/**/*
    - bin/*
    - app/views/**/*
Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/DoubleNegation:
  Enabled: true
  EnforcedStyle: allowed_in_returns

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  Enabled: true

Layout/MultilineOperationIndentation:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/TrailingWhitespace:
  AllowInHeredoc: true
  Enabled: true

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/SpaceInLambdaLiteral:
  Enabled: true
  EnforcedStyle: require_space

Style/CommentAnnotation:
  Enabled: true
  Keywords: INFO, TODO, FIXME, OPTIMIZE, HACK, REVIEW, NOTE

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Layout/LineLength:
  Max: 110

Style/FrozenStringLiteralComment:
  Enabled: true

Naming/VariableNumber:
  Enabled: true
  EnforcedStyle: snake_case

Style/SingleLineBlockParams:
  Methods:
    - reduce:
        - a
        - e
    - inject:
        - a
        - e

Style/Lambda:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false
  Max: 5
  Exclude:
    - app/models/taction.rb
Style/MultipleComparison:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

# TODO: This is important cop, but cannot be safely updated
Rails/SkipsModelValidations:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Naming/MethodParameterName:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false

RSpec/EmptyLineAfterExampleGroup:
  Enabled: true

RSpec/EmptyLineAfterHook:
  Enabled: true

RSpec/EmptyLineAfterExample:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/InstanceVariable:
  Exclude:
    - spec/models/admin/accountant/manager_metric_spec.rb
